# Generated by Django 5.0.6 on 2026-03-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dhemail", "0001_initial"),
        ("lot", "0012_alter_devicebeneficiary_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutiontemplate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="LotTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_templates",
                        to="lot.lot",
                    ),
                ),
            ],
            options={
                "unique_together": {("lot", "template_name")},
            },
        ),
    ]
