#!/bin/sh

# SPDX-License-Identifier: AGPL-3.0-or-later

set -e
set -u
# DEBUG
set -x

prompt_env_var() {
        # Prompt for an env var if unset or empty, with a fallback default.
        # Usage: prompt_env_var VAR_NAME DEFAULT_VALUE

        var_name="${1}"
        default="${2}"
        info="${3:-}"

        # dereference: get current value of the variable named in $var_name
        eval "current=\${${var_name}:-}"

        if [ -z "${current}" ]; then
                if [ "${info}" ]; then
                        info="\n[${var_name}] info:\n${info}\n"
                fi
                # show the default in the prompt
                printf "${info}\n+ Enter value for %s (default is \"%s\"): " "${var_name}" "${default}"
                # read into a temporary
                read answer
                # if they just hit enter, use default
                if [ -z "${answer}" ]; then
                        answer=${default}
                fi
                # export the result back into the named variable
                export "${var_name}"="${answer}"
        fi
}

add_env_var() {
        # add env var to template
        var_name="${1}"
        template_env_vars="${template_env_vars} \${${var_name}}"
}

use_env_var() {
        # prompt env var for completion, and add env var to template

        var_name="${1}"
        default="${2}"
        info="${3:-}"
        prompt_env_var "${var_name}" "${default}" "${info}"
        add_env_var "${var_name}"
}

docker_wizard__idhub_enabled() {
        add_env_var IDHUB_DOMAIN_REQUEST 'idhub.example.org'

        export COMPOSE_PROFILES="${COMPOSE_PROFILES},idhub"

        if echo "${DB_TYPE_REQUEST}" | grep -q 'postgres' ; then
                echo 'idhub-postgres docker profile detected, adding to COMPOSE_PROFILES env var'
                COMPOSE_PROFILES_REQUEST="${COMPOSE_PROFILES_REQUEST},idhub-postgres"
        fi
}

docker_wizard__finalize() {

        # we always need to put at least a domain for IdHub
        if [ "${IDHUB_ENABLED:-}" = 'true' ]; then
                docker_wizard__idhub_enabled
        else
                export IDHUB_DOMAIN_REQUEST='idhub.example.org'
                add_env_var IDHUB_DOMAIN_REQUEST
        fi

        set -x

        if echo "${DB_TYPE_REQUEST}" | grep -q 'postgres' ; then
                echo 'devicehub-postgres docker profile detected, adding to COMPOSE_PROFILES env var'
                COMPOSE_PROFILES_REQUEST="${COMPOSE_PROFILES_REQUEST},devicehub-postgres"
        fi

        if echo "${COMPOSE_PROFILES_REQUEST}" | grep -q 'letsencrypt' ; then
                export RPROXY_ENABLE_LETSENCRYPT_REQUEST=enable
        else
                export RPROXY_ENABLE_LETSENCRYPT_REQUEST=false
        fi
        add_env_var RPROXY_ENABLE_LETSENCRYPT_REQUEST

        if [ "${DEVICEHUB_DEMO_REQUEST}" = 'true' ]; then
                export DEVICEHUB_DEMO_PREDEFINED_TOKEN_REQUEST='5018dd65-9abd-4a62-8896-80f34ac66150'
        fi
        add_env_var DEVICEHUB_DEMO_PREDEFINED_TOKEN_REQUEST

        if [ "${DOCKER_VOLUME_ENABLED:-}" = 'true' ]; then
                export DEVICEHUB_VOLUME_REQUEST=DEVICEHUB_DATA
                export IDHUB_VOLUME_REQUEST=IDHUB_DATA
        else
                export DEVICEHUB_VOLUME_REQUEST=.
                export IDHUB_VOLUME_REQUEST=./idhub
        fi
        add_env_var DEVICEHUB_VOLUME_REQUEST
        add_env_var IDHUB_VOLUME_REQUEST

        # if user is root, place it in /opt
        if [ "$(id -u "${USER}")" = 0 ]; then
                export ROOT_DIR_REQUEST='/opt'
        else
                export ROOT_DIR_REQUEST="${HOME}"
        fi
        add_env_var DEVICEHUB_ROOT_DIR_REQUEST

        # src https://stackoverflow.com/questions/41298963/is-there-a-function-for-generating-settings-secret-key-in-django
        export DEVICEHUB_SECRET_KEY_SECRET_REQUEST="$(python3 -c 'import secrets; print(secrets.token_hex(100))')"
        add_env_var DEVICEHUB_SECRET_KEY_SECRET_REQUEST

        export IDHUB_SECRET_KEY_SECRET_REQUEST="$(python3 -c 'import secrets; print(secrets.token_hex(100))')"
        add_env_var IDHUB_SECRET_KEY_SECRET_REQUEST

        export TIME_ZONE_REQUEST="$(cat /etc/timezone 2>/dev/null || timedatectl | grep "Time zone" | awk '{print $3}' || echo 'UTC')"

        printf '%s\n\n' "# this was autogenerated using wizard_choice: $wizard_choice" > .env
        envsubst "${template_env_vars}" < .env.example >> .env

        # TODO volume map is incorrect (TODO touch file)
        if echo "${COMPOSE_PROFILES_REQUEST}" | grep -q 'letsencrypt' ; then
                echo 'letsencrypt docker profile detected, you should run ./docker/certbot__generate-first-cert.sh before continuing'
                ./docker/certbot__generate-first-cert.sh
        fi
}

docker_wizard__custom() {
        # Custom builds its own template_env_vars dynamically via use_env_var
        template_env_vars=''

        use_env_var DEVICEHUB_HOST_REQUEST 'devicehub.example.org'
        use_env_var DEVICEHUB_PORT_REQUEST '8000'

        use_env_var DEVICEHUB_INIT_ORG_REQUEST 'example-org'
        use_env_var DEVICEHUB_INIT_ADMIN_EMAIL_REQUEST 'user@example.org'
        use_env_var DEVICEHUB_INIT_ADMIN_PASSWORD_SECRET_REQUEST '1234'

        use_env_var DEVICEHUB_DEMO_REQUEST 'false' 'Use false for production and true for development'
        use_env_var REMOVE_DATA_REQUEST 'false' 'Use false for production and true for development'
        use_env_var DOCKER_ALWAYS_BUILD_REQUEST 'false' 'Use false for production and true for development'
        use_env_var DEVICEHUB_DEBUG_REQUEST 'false' 'Use false for production and true for development'

        prompt_env_var DOCKER_VOLUME_ENABLED 'true' 'Use true for production and false for development. When true, uses a docker volume named DEVICEHUB_DATA, when false, maps to current sourcecode'

        docker_profiles_info='Use
  rproxy              if you want to add rproxy (nginx) to docker compose
  rproxy,letsencrypt  for managing a real HTTPS cert
by default does not use rproxy nor letsencrypt'
        use_env_var COMPOSE_PROFILES_REQUEST '' "${docker_profiles_info}"

        use_env_var DB_TYPE_REQUEST 'postgres' 'Use
  postgres  production ready solution
  sqlite    minimalist solution'

        use_env_var DOCKER_RESTART_POLICY_REQUEST 'no' 'Default policy for docker containers: no, unless-stopped, on-failure, always. src https://docs.docker.com/engine/containers/start-containers-automatically/#use-a-restart-policy'
}

docker_wizard__dev() {
        use_env_var DEVICEHUB_HOST_REQUEST 'localhost'
        export DEVICEHUB_PORT_REQUEST='8000'
        export DEVICEHUB_INIT_ORG_REQUEST='example-org'
        export DEVICEHUB_INIT_ADMIN_EMAIL_REQUEST='user@example.org'
        export DEVICEHUB_INIT_ADMIN_PASSWORD_SECRET_REQUEST='1234'
        export DEVICEHUB_DEMO_REQUEST='true'
        export REMOVE_DATA_REQUEST='true'
        export DOCKER_ALWAYS_BUILD_REQUEST='true'
        export DEVICEHUB_DEBUG_REQUEST='true'
        export DOCKER_VOLUME_ENABLED='false'
        use_env_var DB_TYPE_REQUEST 'sqlite' 'Use
  postgres  production ready solution
  sqlite    minimalist solution'
        prompt_env_var IDHUB_ENABLED 'false' 'IdHub is an experimental service to make the devicehub info more verifiable'
        export DOCKER_RESTART_POLICY_REQUEST='no'
}

docker_wizard__prod_noproxy() {
        use_env_var DEVICEHUB_HOST_REQUEST 'devicehub.example.org'
        use_env_var DEVICEHUB_PORT_REQUEST '8000'

        use_env_var DEVICEHUB_INIT_ORG_REQUEST 'example-org'
        use_env_var DEVICEHUB_INIT_ADMIN_EMAIL_REQUEST 'user@example.org'
        use_env_var DEVICEHUB_INIT_ADMIN_PASSWORD_SECRET_REQUEST '1234'

        export DEVICEHUB_DEMO_REQUEST='false'
        export REMOVE_DATA_REQUEST='false'
        export DOCKER_ALWAYS_BUILD_REQUEST='false'
        export DEVICEHUB_DEBUG_REQUEST='false'
        export DOCKER_VOLUME_ENABLED='true'
        export DB_TYPE_REQUEST='postgres'
        export DOCKER_RESTART_POLICY_REQUEST='unless-stopped'
}

docker_wizard__prod() {
        # same base as prod_noproxy, just add more containers
        docker_wizard__prod_noproxy
        export COMPOSE_PROFILES_REQUEST='rproxy,letsencrypt'
}

docker_wizard__selector() {
        # Initialize the template vars string (used by envsubst)
        # We must ensure this list matches the variables defined in .env.example
        template_env_vars='$TIME_ZONE_REQUEST $ROOT_DIR_REQUEST $DB_TYPE_REQUEST $REMOVE_DATA_REQUEST $DOCKER_ALWAYS_BUILD_REQUEST $DOCKER_RESTART_POLICY_REQUEST $DEVICEHUB_HOST_REQUEST $DEVICEHUB_PORT_REQUEST $DEVICEHUB_INIT_ORG_REQUEST $DEVICEHUB_INIT_ADMIN_EMAIL_REQUEST $DEVICEHUB_INIT_ADMIN_PASSWORD_SECRET_REQUEST $DEVICEHUB_DEMO_REQUEST $DEVICEHUB_DEBUG_REQUEST $COMPOSE_PROFILES_REQUEST $DEVICEHUB_SECRET_KEY_SECRET_REQUEST $DEVICEHUB_DEMO_PREDEFINED_TOKEN_REQUEST $DEVICEHUB_VOLUME_REQUEST $RPROXY_ENABLE_LETSENCRYPT_REQUEST $IDHUB_DOMAIN_REQUEST $IDHUB_SECRET_KEY_SECRET_REQUEST $IDHUB_VOLUME_REQUEST'
        export COMPOSE_PROFILES_REQUEST=''

        while true; do
                printf '\nPlease select the installation type (by default, custom):\n'
                printf '  %-12s %s\n'   'custom' 'Answer more detailed questions'
                printf '  %-12s %s\n'   'prod' 'Production (with Postgres, Reverse Proxy, LetsEncrypt)'
                printf '  %-12s %s\n'   'prod_noproxy' 'Production (with Postgres)'
                printf '  %-12s %s\n\n' 'dev' 'Development (with Sqlite, No Proxy, Reset Data on restart)'

                read -p 'Select installation type: ' wizard_choice

                case $wizard_choice in
                        custom)       docker_wizard__custom       ; break ;;
                        dev)          docker_wizard__dev          ; break ;;
                        prod)         docker_wizard__prod         ; break ;;
                        prod_noproxy) docker_wizard__prod_noproxy ; break ;;
                        *) ;;
                esac
        done
}

docker_wizard() {
        set +x
        printf "\nDetected .env file is missing, so let's initialize the config (if you
want to see again, remove .env file)\n\nPress enter to continue... "
        read enter

        docker_wizard__selector

        docker_wizard__finalize
}

main() {
        clear
        cd "$(dirname "${0}")"

        if [ ! -f .env ]; then
                docker_wizard
        fi
        . ./.env
        mkdir -p "${DOCKER_DEVICEHUB_DATA_DIR}"

        if [ "${DEVICEHUB_REMOVE_DATA}" = 'true' ]; then
                docker compose down -v
        else
                docker compose down
        fi

        if [ "${DOCKER_ALWAYS_BUILD:-}" = 'true' ]; then
                docker compose build
        fi
        docker compose up ${detach_arg:-}
}

main "${@}"

# written in emacs
# -*- mode: shell-script; -*-
