# Generated by Django 5.0.6 on 2024-06-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "software",
                    models.CharField(
                        choices=[("Workbench", "Workbench")],
                        default="Workbench",
                        max_length=32,
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("version", models.CharField(max_length=32)),
                ("sid", models.CharField(max_length=32)),
                ("settings_version", models.CharField(max_length=32)),
                ("is_server_erase", models.BooleanField(default=False)),
                (
                    "severity",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Info"),
                            (1, "Notice"),
                            (2, "Warning"),
                            (3, "Error"),
                        ],
                        default=0,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("components", models.ManyToManyField(to="device.component")),
                (
                    "computer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="device.computer",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
