# Generated by Django 5.0.6 on 2024-07-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snapshot", "0002_alter_snapshot_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshot",
            name="start_time",
        ),
    ]
