# Generated by Django 5.0.6 on 2025-07-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
