# Generated by Django 5.0.6 on 2024-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dpp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberFederated",
            fields=[
                (
                    "dlt_id_provider",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("domain", models.CharField(max_length=256)),
                ("client_id", models.CharField(max_length=256)),
                ("client_secret", models.CharField(max_length=256)),
            ],
        ),
    ]
