# Generated by Django 5.0.6 on 2024-11-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dpp", "0002_memberfederated"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="memberfederated",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.institution",
            ),
        ),
        migrations.AlterField(
            model_name="memberfederated",
            name="client_id",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="memberfederated",
            name="client_secret",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.CreateModel(
            name="UserDpp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roles_dlt", models.TextField()),
                ("api_keys_dlt", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
