# Generated by Django 5.1.3 on 2025-10-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_is_circuit_manager_user_is_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLifecycleMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device_chid', models.CharField(db_index=True, max_length=256, unique=True)),
                ('total_usage_time', models.IntegerField(default=0, help_text='T_T: Total accumulated powered-on hours')),
                ('reuse_time', models.IntegerField(default=0, help_text='T_R: Hours of reuse (second life)')),
                ('evidence_count', models.IntegerField(default=0)),
                ('disk_change_count', models.IntegerField(default=0)),
                ('first_evidence_uuid', models.UUIDField(blank=True, null=True)),
                ('last_evidence_uuid', models.UUIDField(blank=True, null=True)),
                ('first_poh', models.IntegerField(blank=True, help_text='Power-on hours from the first evidence', null=True)),
                ('last_poh', models.IntegerField(blank=True, help_text='Power-on hours from the last evidence', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institution')),
            ],
            options={
                'verbose_name': 'Device Lifecycle Metric',
                'verbose_name_plural': 'Device Lifecycle Metrics',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='DiskChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device_chid', models.CharField(db_index=True, max_length=256)),
                ('evidence_uuid', models.UUIDField(db_index=True)),
                ('evidence_index', models.IntegerField(help_text='Index in chronological sequence (0 = first evidence)')),
                ('old_disk_serial', models.CharField(blank=True, max_length=256, null=True)),
                ('new_disk_serial', models.CharField(blank=True, max_length=256, null=True)),
                ('old_disk_model', models.CharField(blank=True, max_length=256, null=True)),
                ('new_disk_model', models.CharField(blank=True, max_length=256, null=True)),
                ('poh_before_change', models.IntegerField(blank=True, help_text='PoH from evidence before disk change', null=True)),
                ('poh_after_change', models.IntegerField(blank=True, help_text='PoH from evidence with new disk', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institution')),
            ],
            options={
                'ordering': ['device_chid', 'evidence_index'],
                'indexes': [models.Index(fields=['device_chid', 'evidence_index'], name='environment_device__5b9962_idx')],
                'unique_together': {('device_chid', 'evidence_uuid')},
            },
        ),
    ]
