# Generated by Django 5.0.6 on 2026-05-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environmental_impact", "0001_initial"),
        ("user", "0005_institution_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceEnvironmentalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("device_chid", models.CharField(db_index=True, max_length=256)),
                ("country", models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                "ordering": ["device_chid"],
            },
        ),
        migrations.RenameIndex(
            model_name="diskchangeevent",
            new_name="disk_change_device__f7da51_idx",
            old_name="environment_device__5b9962_idx",
        ),
        migrations.AlterField(
            model_name="devicelifecyclemetrics",
            name="reuse_time",
            field=models.IntegerField(
                default=0, help_text="Hours of reuse (second life)"
            ),
        ),
        migrations.AlterField(
            model_name="devicelifecyclemetrics",
            name="total_usage_time",
            field=models.IntegerField(
                default=0, help_text="Total accumulated powered-on hours"
            ),
        ),
        migrations.AlterModelTable(
            name="diskchangeevent",
            table="disk_change_events",
        ),
        migrations.AddField(
            model_name="deviceenvironmentalprofile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.institution"
            ),
        ),
        migrations.AddConstraint(
            model_name="deviceenvironmentalprofile",
            constraint=models.UniqueConstraint(
                fields=("device_chid", "owner"), name="env_profile_unique_device_owner"
            ),
        ),
    ]
