# Generated by Django 5.0.6 on 2026-06-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0004_alter_institution_algorithm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("root", models.CharField(max_length=256)),
                ("shortid", models.CharField(default="", max_length=256)),
                ("type", models.CharField(default="", max_length=256)),
                ("manufacturer", models.CharField(default="", max_length=256)),
                ("model", models.CharField(default="", max_length=256)),
                ("serial", models.CharField(default="", max_length=256)),
                ("cpu_model", models.CharField(default="", max_length=256)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("data", models.JSONField(default=dict)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.institution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["owner", "-last_updated"],
                        name="productcache_owner_lastupd_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productcache",
            constraint=models.UniqueConstraint(
                fields=("owner", "root"), name="productcache_unique"
            ),
        ),
    ]
