# Generated by Django 5.0.6 on 2024-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="brand",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="devicehub_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="variant",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
