# Generated by Django 5.0.6 on 2026-08-10 12:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

# Frozen copy of device.models.DEFAULT_PRODUCT_TYPES: migrations must not
# depend on application code that may change later.
DEFAULT_PRODUCT_TYPES = [
    "Desktop",
    "Laptop",
    "Server",
    "GraphicCard",
    "HardDrive",
    "SolidStateDrive",
    "Motherboard",
    "NetworkAdapter",
    "Processor",
    "RamModule",
    "SoundCard",
    "Display",
    "Battery",
    "Camera",
    "Switch",
    "Router",
    "RouterWifi",
]


def create_default_product_types(apps, schema_editor):
    Institution = apps.get_model("user", "Institution")
    DeviceType = apps.get_model("device", "DeviceType")

    for institution in Institution.objects.all():
        DeviceType.objects.bulk_create([
            DeviceType(institution=institution, name=name, order=order)
            for order, name in enumerate(DEFAULT_PRODUCT_TYPES, start=1)
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
        ("user", "0007_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="devicetype",
            constraint=models.UniqueConstraint(
                models.F("institution"),
                django.db.models.functions.text.Lower("name"),
                name="unique_institution_device_type",
            ),
        ),
        migrations.RunPython(
            create_default_product_types,
            migrations.RunPython.noop,
        ),
    ]
