# Generated by Django 5.0.6 on 2024-07-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
