# Generated by Django 5.0.6 on 2024-07-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_device_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
