# Generated by Django 5.0.6 on 2026-08-13 16:34

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0002_devicetype_devicetype_unique_institution_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetype",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="DeviceTypeAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "device_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="device.devicetype",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="devicetypeattribute",
            constraint=models.UniqueConstraint(
                models.F("device_type"),
                django.db.models.functions.text.Lower("name"),
                name="unique_device_type_attribute",
            ),
        ),
    ]
