# Generated by Django 5.0.6 on 2024-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_device_manufacturer"),
        ("lot", "0002_remove_lot_devices_devicelot"),
        ("snapshot", "0002_remove_annotation_device"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Device",
        ),
    ]
