# Generated by Django 5.0.6 on 2024-07-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0003_remove_component_type_remove_computer_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="dhid_bk",
        ),
        migrations.RemoveField(
            model_name="device",
            name="phid_bk",
        ),
        migrations.AddField(
            model_name="computer",
            name="erasure_server",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="reliable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="computer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="device.computer",
            ),
        ),
        migrations.AlterField(
            model_name="computer",
            name="system_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
