# Generated by Django 5.0.6 on 2025-11-18 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_user_is_circuit_manager_user_is_shop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("issuer_did", models.CharField(max_length=64)),
                ("organization_did", models.CharField(max_length=64)),
                ("organization_name", models.CharField(max_length=64)),
                ("str_credential", models.CharField(max_length=5000)),
                ("reference", models.CharField(max_length=64, null=True)),
                ("api_destination", models.CharField(max_length=5000, null=True)),
                ("token_destination", models.CharField(max_length=5000, null=True)),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(0, "Sended"), (1, "Received")], default=0
                    ),
                ),
                ("sended", models.BooleanField(default=False)),
                ("credential_id", models.CharField(max_length=64)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.institution",
                    ),
                ),
            ],
        ),
    ]
