# Generated by Django 5.0.6 on 2025-10-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_user_is_circuit_manager_user_is_shop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer_did", models.CharField(max_length=64)),
                ("destination_did", models.CharField(max_length=64)),
                ("destination_name", models.CharField(max_length=64)),
                ("credential", models.CharField(max_length=5000)),
                ("api_destination", models.CharField(max_length=5000)),
                ("token_destination", models.CharField(max_length=5000)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.institution",
                    ),
                ),
            ],
        ),
    ]
