# Generated by Django 5.0.6 on 2025-10-31 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
