# Generated by Django 5.0.6 on 2025-11-07 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transfer",
            name="type",
            field=models.SmallIntegerField(
                choices=[(0, "Sended"), (1, "Received")], default=0
            ),
        ),
    ]
