"""ISO 3166-1 alpha-3 to alpha-2 codes for the countries Our World in Data reports."""


def alpha3_to_alpha2(country_code: str) -> str | None:
    mapping = {
        "AFG": "AF", "ALB": "AL", "DZA": "DZ", "ASM": "AS", "AGO": "AO",
        "ATG": "AG", "ARG": "AR", "ARM": "AM", "ABW": "AW", "AUS": "AU",
        "AUT": "AT", "AZE": "AZ", "BHS": "BS", "BHR": "BH", "BGD": "BD",
        "BRB": "BB", "BLR": "BY", "BEL": "BE", "BLZ": "BZ", "BEN": "BJ",
        "BMU": "BM", "BTN": "BT", "BOL": "BO", "BIH": "BA", "BWA": "BW",
        "BRA": "BR", "VGB": "VG", "BRN": "BN", "BGR": "BG", "BFA": "BF",
        "BDI": "BI", "KHM": "KH", "CMR": "CM", "CAN": "CA", "CPV": "CV",
        "CYM": "KY", "CAF": "CF", "TCD": "TD", "CHL": "CL", "CHN": "CN",
        "COL": "CO", "COM": "KM", "COG": "CG", "COD": "CD", "COK": "CK",
        "CRI": "CR", "CIV": "CI", "HRV": "HR", "CUB": "CU", "CYP": "CY",
        "CZE": "CZ", "DNK": "DK", "DJI": "DJ", "DMA": "DM", "DOM": "DO",
        "ECU": "EC", "EGY": "EG", "SLV": "SV", "GNQ": "GQ", "ERI": "ER",
        "EST": "EE", "SWZ": "SZ", "ETH": "ET", "FRO": "FO", "FJI": "FJ",
        "FIN": "FI", "FRA": "FR", "GUF": "GF", "PYF": "PF", "GAB": "GA",
        "GMB": "GM", "GEO": "GE", "DEU": "DE", "GHA": "GH", "GIB": "GI",
        "GRC": "GR", "GRL": "GL", "GRD": "GD", "GLP": "GP", "GUM": "GU",
        "GTM": "GT", "GIN": "GN", "GNB": "GW", "GUY": "GY", "HTI": "HT",
        "HND": "HN", "HKG": "HK", "HUN": "HU", "ISL": "IS", "IND": "IN",
        "IDN": "ID", "IRN": "IR", "IRQ": "IQ", "IRL": "IE", "ISR": "IL",
        "ITA": "IT", "JAM": "JM", "JPN": "JP", "JOR": "JO", "KAZ": "KZ",
        "KEN": "KE", "KIR": "KI", "XKX": "XK", "KWT": "KW", "KGZ": "KG",
        "LAO": "LA", "LVA": "LV", "LBN": "LB", "LSO": "LS", "LBR": "LR",
        "LBY": "LY", "LTU": "LT", "LUX": "LU", "MAC": "MO", "MDG": "MG",
        "MWI": "MW", "MYS": "MY", "MDV": "MV", "MLI": "ML", "MLT": "MT",
        "MTQ": "MQ", "MRT": "MR", "MUS": "MU", "MEX": "MX", "FSM": "FM",
        "MDA": "MD", "MNG": "MN", "MNE": "ME", "MSR": "MS", "MAR": "MA",
        "MOZ": "MZ", "MMR": "MM", "NAM": "NA", "NRU": "NR", "NPL": "NP",
        "NLD": "NL", "NCL": "NC", "NZL": "NZ", "NIC": "NI", "NER": "NE",
        "NGA": "NG", "NIU": "NU", "PRK": "KP", "MKD": "MK", "MNP": "MP",
        "NOR": "NO", "OMN": "OM", "PAK": "PK", "PSE": "PS", "PAN": "PA",
        "PNG": "PG", "PRY": "PY", "PER": "PE", "PHL": "PH", "POL": "PL",
        "PRT": "PT", "PRI": "PR", "QAT": "QA", "REU": "RE", "ROU": "RO",
        "RUS": "RU", "RWA": "RW", "SHN": "SH", "KNA": "KN", "LCA": "LC",
        "SPM": "PM", "VCT": "VC", "WSM": "WS", "STP": "ST", "SAU": "SA",
        "SEN": "SN", "SRB": "RS", "SYC": "SC", "SLE": "SL", "SGP": "SG",
        "SVK": "SK", "SVN": "SI", "SLB": "SB", "SOM": "SO", "ZAF": "ZA",
        "KOR": "KR", "SSD": "SS", "ESP": "ES", "LKA": "LK", "SDN": "SD",
        "SUR": "SR", "SWE": "SE", "CHE": "CH", "SYR": "SY", "TWN": "TW",
        "TJK": "TJ", "TZA": "TZ", "THA": "TH", "TGO": "TG", "TON": "TO",
        "TTO": "TT", "TUN": "TN", "TUR": "TR", "TKM": "TM", "TCA": "TC",
        "TUV": "TV", "UGA": "UG", "UKR": "UA", "ARE": "AE", "GBR": "GB",
        "USA": "US", "VIR": "VI", "URY": "UY", "UZB": "UZ", "VUT": "VU",
        "VEN": "VE", "VNM": "VN", "ESH": "EH", "YEM": "YE", "ZMB": "ZM",
        "ZWE": "ZW",
    }
    return mapping.get(country_code)
