# Generated by Django 5.0.6 on 2026-08-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0002_devicelog_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="statedefinition",
            name="auto_issue_dte",
            field=models.BooleanField(default=False),
        ),
    ]
