# Generated by Django 5.0.6 on 2026-02-12 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0002_devicelog_note"),
        ("evidence", "0007_rootalias_rootalias_rootalias_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="system_property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evidence.systemproperty",
            ),
        ),
    ]
