# Generated by Django 5.0.6 on 2024-07-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="devices",
        ),
        migrations.CreateModel(
            name="DeviceLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=256)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
            ],
        ),
    ]
