# Generated by Django 5.0.6 on 2024-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
