# Generated by Django 5.0.6 on 2024-09-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0002_lotannotation"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.institution"
            ),
        ),
        migrations.AlterField(
            model_name="lotannotation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.institution"
            ),
        ),
        migrations.AlterField(
            model_name="lottag",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.institution"
            ),
        ),
    ]
