# Generated by Django 5.0.6 on 2025-01-31 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0005_alter_lotproperty_type'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lotproperty',
            constraint=models.UniqueConstraint(fields=('key', 'lot'), name='property_unique_type_key_lot'),
        ),
    ]
