# Generated by Django 5.0.6 on 2025-02-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0006_lotproperty_property_unique_type_key_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottag',
            name='inbox',
            field=models.BooleanField(default=False),
        ),
    ]
