# Generated by Django 5.0.6 on 2025-02-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0007_lottag_inbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot',
            old_name='closed',
            new_name='archived',
        ),
    ]
