# Generated by Django 5.0.6 on 2025-02-21 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0007_lottag_inbox"),
        ("user", "0002_institution_algorithm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_institution_and_name"
            ),
        ),
    ]
