# Generated by Django 5.0.6 on 2025-03-10 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0008_rename_closed_lot_archived"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reconciliation",
                    models.BooleanField(default=False, verbose_name="Reconciliation"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email address"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_circuit_manager",
                    models.BooleanField(
                        default=False, verbose_name="is circuit manager"
                    ),
                ),
                ("is_shop", models.BooleanField(default=False, verbose_name="is shop")),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="lotsubscription",
            constraint=models.UniqueConstraint(
                fields=("lot", "user"), name="unique_lot_user"
            ),
        ),
    ]
