# Generated by Django 5.0.6 on 2025-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0008_rename_closed_lot_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottag",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
