# Generated by Django 5.0.6 on 2025-03-05 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0008_rename_closed_lot_archived"),
        ("user", "0002_institution_algorithm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("owner", "name", "type"), name="unique_institution_and_name"
            ),
        ),
    ]
