# Generated by Django 5.0.6 on 2025-03-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0009_lotsubscription_lotsubscription_unique_lot_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="donor",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lotsubscription",
            name="is_circuit_manager",
            field=models.BooleanField(default=False, verbose_name="is circuit manager"),
        ),
        migrations.AddField(
            model_name="lotsubscription",
            name="is_shop",
            field=models.BooleanField(default=False, verbose_name="is shop"),
        ),
    ]
