# Generated by Django 5.0.6 on 2025-03-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0009_lot_unique_institution_and_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottag",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
