# Generated by Django 5.0.6 on 2025-03-13 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0009_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sign_conditions",
                    models.BooleanField(default=False, verbose_name="Conditions"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email address"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lot.lotsubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=256)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lot.beneficiary",
                    ),
                ),
            ],
        ),
    ]
