# Generated by Django 5.0.6 on 2025-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0010_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicebeneficiary",
            name="returned_place",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
