# Generated by Django 5.0.6 on 2026-01-27 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0010_lottag_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sign_conditions",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Conditions"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email address"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=256)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Available"),
                            (1, "Interest"),
                            (2, "Confirmed"),
                            (3, "Delivered"),
                            (4, "Returned"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "returned_place",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lot.beneficiary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                ("address", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "representative",
                    models.CharField(max_length=64, verbose_name="Representative"),
                ),
                (
                    "reconciliation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reconciliation"
                    ),
                ),
                (
                    "accept_contract",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Contract"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email address"),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LotSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "representative",
                    models.CharField(max_length=64, verbose_name="Representative"),
                ),
                (
                    "established_in",
                    models.CharField(max_length=64, verbose_name="Established in"),
                ),
                ("location", models.CharField(max_length=64, verbose_name="Location")),
                (
                    "committee",
                    models.CharField(
                        max_length=64, verbose_name="Monitoring Committee Donee members"
                    ),
                ),
                (
                    "subannex2",
                    models.CharField(
                        max_length=64, verbose_name="Subannex2 recipient entity name"
                    ),
                ),
                (
                    "jurisdiction_city",
                    models.CharField(max_length=64, verbose_name="Jurisdiction City"),
                ),
                (
                    "agreement_place",
                    models.CharField(max_length=64, verbose_name="Agreement place"),
                ),
                ("agreement_date", models.DateTimeField(verbose_name="Agreement date")),
                (
                    "apendix_1b_date",
                    models.DateTimeField(verbose_name="Apendix 1b date"),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[(0, "Circuit Manager"), (1, "Shop")]
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lot.lot"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lot.lotsubscription"
            ),
        ),
        migrations.AddConstraint(
            model_name="lotsubscription",
            constraint=models.UniqueConstraint(
                fields=("lot", "user"), name="unique_lot_user"
            ),
        ),
    ]
