# Generated by Django 5.0.6 on 2025-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0010_beneficiary_devicebeneficiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicebeneficiary",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Available"),
                    (1, "Interest"),
                    (2, "Confirmed"),
                    (3, "Delivered"),
                    (4, "Returned"),
                ],
                default=0,
            ),
        ),
    ]
