# Generated by Django 5.0.6 on 2026-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="accept_contract",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Contract"),
        ),
    ]
