# Generated by Django 5.0.6 on 2025-11-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transfer.transfer",
            ),
        ),
    ]
