# Generated by Django 5.0.6 on 2026-01-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="devicelot",
            constraint=models.UniqueConstraint(
                fields=("lot", "device_id"), name="unique_device_id_and_lot"
            ),
        ),
    ]
