# Generated by Django 5.0.6 on 2026-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebeneficiary",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Available"),
                    (1, "Interested"),
                    (2, "Confirmed"),
                    (3, "Delivered"),
                    (4, "Returned"),
                ],
                default=0,
            ),
        ),
    ]
