# Generated by Django 5.0.6 on 2025-10-29 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issuer_did", models.CharField(max_length=64)),
                ("destination_did", models.CharField(max_length=64)),
                ("destination_name", models.CharField(max_length=64)),
                ("credential", models.CharField(max_length=5000)),
                ("api_destination", models.CharField(max_length=5000)),
                ("token_destination", models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name="lottag",
            name="transfer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lot.transfer",
            ),
        ),
    ]
