# Generated by Django 5.0.6 on 2026-01-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0012_donor_accept_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="donor",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lotsubscription",
            name="address",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="lotsubscription",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
