# Generated by Django 5.0.6 on 2026-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0012_canonical_device_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicebeneficiary",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Available"),
                    (1, "Interested"),
                    (2, "Confirmed"),
                    (3, "Delivered"),
                    (4, "Returned"),
                ],
                default=0,
            ),
        ),
    ]
