# Generated by Django 5.0.6 on 2026-10-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lot", "0013_alter_devicebeneficiary_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lottag",
            name="exclusive_devices",
            field=models.BooleanField(default=False),
        ),
    ]
