# Generated by Django 5.0.6 on 2025-02-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_circuit_manager',
            field=models.BooleanField(default=False, verbose_name='is circuit manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='is shop'),
        ),
    ]
