# Generated by Django 5.0.6 on 2025-02-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_circuit_manager_user_is_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_circuit_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_shop',
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_circuit_manager', models.BooleanField(default=False, verbose_name='is circuit manager')),
                ('is_shop', models.BooleanField(default=False, verbose_name='is shop')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution')},
            },
        ),
    ]
