# Generated by Django 5.0.6 on 2025-03-20 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_institution_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_circuit_manager",
            field=models.BooleanField(default=False, verbose_name="is circuitmanager"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_shop",
            field=models.BooleanField(default=False, verbose_name="is shop"),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="user.institution",
            ),
        ),
    ]
