# Generated by Django 5.0.6 on 2025-12-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_circuit_manager_user_is_shop_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("ereuse24", "ereuse24"),
                    ("ereuse22", "ereuse22"),
                    ("photo25", "photo25"),
                ],
                default="ereuse24",
                max_length=30,
            ),
        ),
    ]
