# Generated by Django 5.0.6 on 2025-11-12 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0002_devicelog_note"),
        ("lot", "0011_beneficiary_devicebeneficiary_donor_lotsubscription_and_more"),
        ("user", "0003_user_is_circuit_manager_user_is_shop_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("es", "español"),
                            ("en", "english"),
                            ("ca", "català"),
                        ],
                        default="en-us",
                        help_text="The user's preferred language for the interface.",
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                (
                    "pinned_lots",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Lots the user wants to see on their dashboard.",
                        to="lot.lot",
                    ),
                ),
                (
                    "pinned_states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="States the user wants to see on their dashboard.",
                        to="action.statedefinition",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
