# Generated by Django 5.0.6 on 2026-02-03 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_institution_algorithm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="location",
        ),
        migrations.AddField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 code.",
                max_length=2,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$",
                        "Must be a 2-letter uppercase ISO code (e.g. AU, DE)",
                    )
                ],
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="facility_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Facility Description"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="facility_id_uri",
            field=models.URLField(
                blank=True,
                help_text="Globally unique URI.",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "did"]
                    )
                ],
                verbose_name="Facility ID (URI)",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="locality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City/Locality"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State/Region"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Logo URL"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(
                help_text="Official registered name of the organization.",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="responsable_person",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Responsable Person"
            ),
        ),
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        help_text="The root URL of the IdHub instance (e.g., https://idhub.example.com/api/v1/)",
                        verbose_name="Signing Service Base URL",
                    ),
                ),
                (
                    "signing_auth_token",
                    models.CharField(
                        blank=True,
                        help_text="Bearer token for the signing service.",
                        max_length=1024,
                        null=True,
                        verbose_name="Signing API Token",
                    ),
                ),
                (
                    "issuer_did",
                    models.CharField(
                        blank=True,
                        help_text="The DID used by this client on the signing service.",
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^did:[a-z0-9]+:.+", "Invalid DID format"
                            )
                        ],
                        verbose_name="Issuer DID",
                    ),
                ),
                (
                    "schema_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Map 'credential_type' (keys) to 'schema_filename' (values).",
                        verbose_name="Schema Mapping",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("ereuse24", "ereuse24"),
                            ("ereuse22", "ereuse22"),
                            ("photo25", "photo25"),
                        ],
                        default="ereuse24",
                        help_text="The default algorithm used for device aggregation.",
                        max_length=30,
                        verbose_name="Algorithm",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="user.institution",
                    ),
                ),
            ],
        ),
    ]
