# Generated by Django 5.0.6 on 2025-12-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_institution_algorithm"),
        ("user", "0004_userprofile"),
    ]

    operations = []
