# Generated by Django 5.0.6 on 2026-01-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_institution_algorithm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="location",
        ),
        migrations.AddField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 code (e.g., AU, US, DE).",
                max_length=2,
                null=True,
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="facility_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Facility Description"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="facility_id_uri",
            field=models.URLField(
                blank=True,
                help_text="Globally unique URI for this facility (e.g. https://...)",
                max_length=500,
                null=True,
                verbose_name="Facility ID (URI)",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="locality",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City/Locality"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State/Region"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Logo URL"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(
                help_text="Official registered name of the organization.",
                max_length=255,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="responsable_person",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Responsable Person"
            ),
        ),
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("ereuse24", "ereuse24"),
                            ("ereuse22", "ereuse22"),
                            ("photo25", "photo25"),
                        ],
                        default="ereuse24",
                        help_text="The default algorithm used for device aggregation.",
                        max_length=30,
                        verbose_name="Algorithm",
                    ),
                ),
                (
                    "issuer_did",
                    models.CharField(
                        blank=True,
                        help_text="The W3C DID (e.g., did:web:example.com) that is used on the idhub service.",
                        max_length=255,
                        null=True,
                        verbose_name="Issuer DID",
                    ),
                ),
                (
                    "signing_service_domain",
                    models.URLField(
                        blank=True,
                        help_text="Idhub endpoint where the credential will be signed.",
                        null=True,
                        verbose_name="Signing Service URL",
                    ),
                ),
                (
                    "signing_auth_token",
                    models.CharField(
                        blank=True,
                        help_text="Bearer token for the signing service.",
                        max_length=1024,
                        null=True,
                        verbose_name="Signing API Token",
                    ),
                ),
                (
                    "device_dpp_schema",
                    models.CharField(
                        blank=True,
                        help_text="Filename of the dpp credential schema found on your idhub provider.",
                        max_length=255,
                        null=True,
                        verbose_name="Device schema name",
                    ),
                ),
                (
                    "untp_drf_schema",
                    models.CharField(
                        blank=True,
                        help_text="Filename of the drf schema found on your idhub provider.",
                        max_length=255,
                        null=True,
                        verbose_name="UNTP's Digital Facility Record schema name",
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="user.institution",
                        verbose_name="Institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution Settings",
                "verbose_name_plural": "Institution Settings",
            },
        ),
    ]
