# Generated by Django 5.0.6 on 2026-05-20 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_institution_country_institution_facility_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_font_size",
            field=models.PositiveIntegerField(
                default=4,
                help_text="Base text size for properties. Header is scaled slightly larger.",
                validators=[
                    django.core.validators.MinValueValidator(4),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Font Size (pt)",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_height_mm",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Set to 0 for adaptive.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Label Height (mm)",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_label_columns",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Set to 0 for adaptive.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Labels per row",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_label_orientation",
            field=models.CharField(
                choices=[
                    ("HORIZONTAL", "Horizontal (Landscape)"),
                    ("VERTICAL", "Vertical (Portrait)"),
                ],
                default="HORIZONTAL",
                help_text="Only applies to Version 2.",
                max_length=15,
                verbose_name="Label Orientation",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_label_version",
            field=models.CharField(
                choices=[
                    ("V1", "Version 1 (Classic)"),
                    ("V2", "Version 2 (Modern Customizable)"),
                ],
                default="V1",
                help_text="Select the visual template for the labels.",
                max_length=2,
                verbose_name="Label Version",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="qr_width_mm",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Set to 0 for adaptive.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(200),
                ],
                verbose_name="Label Width (mm)",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 code (e.g., AU, US, DE).",
                max_length=2,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$",
                        "Must be a 2-letter uppercase ISO code (e.g. AU, DE)",
                    )
                ],
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="facility_description",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the facility's main activities and scope.",
                null=True,
                verbose_name="Facility Description",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="facility_id_uri",
            field=models.URLField(
                blank=True,
                help_text="Globally unique URI for this facility (e.g., did:web:example.com).",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "did"]
                    )
                ],
                verbose_name="Facility ID (URI)",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="The city, town, or locality name.",
                max_length=100,
                null=True,
                verbose_name="City/Locality",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="A public URL pointing to the organization's logo image.",
                max_length=255,
                null=True,
                verbose_name="Logo URL",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="The postal or ZIP code.",
                max_length=20,
                null=True,
                verbose_name="Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="The state, province, or geographic region.",
                max_length=100,
                null=True,
                verbose_name="State/Region",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="responsable_person",
            field=models.CharField(
                blank=True,
                help_text="The primary person responsible for the operations at this facility.",
                max_length=255,
                null=True,
                verbose_name="Responsible Person",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="The physical street address of the facility.",
                max_length=255,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="supervisor_person",
            field=models.CharField(
                blank=True,
                help_text="The person supervising this facility or organization.",
                max_length=255,
                null=True,
                verbose_name="Supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="institution",
            field=models.OneToOneField(
                help_text="The institution these settings belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="user.institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_content_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No QR on label"),
                    ("INTERNAL", "Internal Device ID"),
                    ("INVENTORY", "Device inventory URL"),
                    ("PUBLIC", "Public Device View"),
                ],
                default="INTERNAL",
                help_text="Determines what data is embedded inside the QR code.",
                max_length=20,
                verbose_name="QR Code Content",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_include_logo",
            field=models.BooleanField(
                default=True,
                help_text="Check to include the institution's logo (if exists) on printed QR labels.",
                verbose_name="Print Institution Logo",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_label_header",
            field=models.CharField(
                blank=True,
                default="Property of ...",
                help_text="Text printed at the top of the label.",
                max_length=100,
                verbose_name="Label Header Text",
            ),
        ),
    ]
