# Generated by Django 5.0.6 on 2026-05-14 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_institution_country_institution_facility_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionsettings",
            name="api_base_url",
            field=models.URLField(
                blank=True,
                help_text="The root URL of the IdHub instance (e.g., https://idhub.example.com/api/v1/)",
                max_length=1024,
                null=True,
                verbose_name="Signing Service Base URL",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="issuer_did",
            field=models.CharField(
                blank=True,
                help_text="The DID used by this client on the signing service.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^did:[a-z0-9]+:.+", "Invalid DID format"
                    )
                ],
                verbose_name="Issuer DID",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="schema_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map 'credential_type' (keys) to 'schema_filename' (values).",
                verbose_name="Schema Mapping",
            ),
        ),
        migrations.AddField(
            model_name="institutionsettings",
            name="signing_auth_token",
            field=models.CharField(
                blank=True,
                help_text="Bearer token for the signing service.",
                max_length=1024,
                null=True,
                verbose_name="Signing API Token",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 3166-1 alpha-2 code (e.g., AU, US, DE).",
                max_length=2,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$",
                        "Must be a 2-letter uppercase ISO code (e.g. AU, DE)",
                    )
                ],
                verbose_name="Country of Operation",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="facility_description",
            field=models.TextField(
                blank=True,
                help_text="A detailed description of the facility's main activities and scope.",
                null=True,
                verbose_name="Facility Description",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="facility_id_uri",
            field=models.URLField(
                blank=True,
                help_text="Globally unique URI for this facility (e.g., did:web:example.com).",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "did"]
                    )
                ],
                verbose_name="Facility ID (URI)",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="The city, town, or locality name.",
                max_length=100,
                null=True,
                verbose_name="City/Locality",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=models.CharField(
                blank=True,
                help_text="A public URL pointing to the organization's logo image.",
                max_length=255,
                null=True,
                verbose_name="Logo URL",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="The postal or ZIP code.",
                max_length=20,
                null=True,
                verbose_name="Postal Code",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="The state, province, or geographic region.",
                max_length=100,
                null=True,
                verbose_name="State/Region",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="responsable_person",
            field=models.CharField(
                blank=True,
                help_text="The primary person responsible for the operations at this facility.",
                max_length=255,
                null=True,
                verbose_name="Responsible Person",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="The physical street address of the facility.",
                max_length=255,
                null=True,
                verbose_name="Street Address",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="supervisor_person",
            field=models.CharField(
                blank=True,
                help_text="The person supervising this facility or organization.",
                max_length=255,
                null=True,
                verbose_name="Supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="institution",
            field=models.OneToOneField(
                help_text="The institution these settings belong to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="user.institution",
                verbose_name="Institution",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_include_logo",
            field=models.BooleanField(
                default=True,
                help_text="Check to include the institution's logo (if exists) on printed QR labels.",
                verbose_name="Print Institution Logo",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_label_header",
            field=models.CharField(
                blank=True,
                default="Property of ...",
                help_text="Text printed at the top of the label.",
                max_length=100,
                verbose_name="Label Header Text",
            ),
        ),
    ]
