# Generated by Django 5.0.6 on 2026-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_institution_process_category_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionlabelsettings",
            name="qr_content_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No QR on label"),
                    ("INTERNAL", "Internal Device ID"),
                    ("INVENTORY", "Device inventory URL"),
                    ("PUBLIC", "Public Device View"),
                    ("DPP", "DPP URL (DPP or Inventory)"),
                    ("DID", "DID (Fallback to Short ID)"),
                ],
                default="INTERNAL",
                help_text="Determines what data is embedded inside the QR code.",
                max_length=20,
                verbose_name="QR Code Content",
            ),
        ),
    ]
