# Generated by Django 5.0.6 on 2026-07-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_institution_process_category_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutiondppsettings",
            name="schema_config",
        ),
        migrations.AddField(
            model_name="institutiondppsettings",
            name="dfr_schema",
            field=models.CharField(
                default="DigitalFacilityRecord.json",
                help_text="Active schema for Facility Records",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="institutiondppsettings",
            name="dpp_schema",
            field=models.CharField(
                default="DigitalProductPassport.json",
                help_text="Active schema for Product Passports",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="institutiondppsettings",
            name="dte_schema",
            field=models.CharField(
                default="DigitalTraceabilityEvent.json",
                help_text="Active schema for Traceability Events (Make/Move/Modify)",
                max_length=255,
            ),
        ),
    ]
