# Generated by Django 5.0.6 on 2026-08-18 08:45

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="algorithm",
            field=models.CharField(
                choices=[
                    ("ereuse24", "ereuse24"),
                    ("ereuse22", "ereuse22"),
                    ("photo25", "photo25"),
                ],
                default="ereuse24",
                help_text="The default algorithm used for product aggregation.",
                max_length=30,
                verbose_name="Algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_content_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No QR on label"),
                    ("INTERNAL", "Internal Product ID"),
                    ("INVENTORY", "Product inventory URL"),
                    ("PUBLIC", "Public Product View"),
                ],
                default="INTERNAL",
                help_text="Determines what data is embedded inside the QR code.",
                max_length=20,
                verbose_name="QR Code Content",
            ),
        ),
        migrations.AlterField(
            model_name="institutionsettings",
            name="qr_printed_properties",
            field=models.JSONField(
                blank=True,
                default=user.models.default_printed_properties,
                help_text="List of product properties (e.g., 'ram', 'cpu', 'storage') to print alongside the QR code.",
                verbose_name="Properties to Print",
            ),
        ),
    ]
