# Generated by Django 5.0.6 on 2026-06-05 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_institutionsettings_qr_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="process_category_code",
            field=models.CharField(
                choices=[
                    ("9511", "Repair of computers and peripheral equipment (9511)"),
                    ("3830", "Materials recovery and recycling (3830)"),
                    ("3313", "Repair of electronic and optical equipment (3313)"),
                    ("4649", "Wholesale of other household goods (4649)"),
                    ("0000", "Other / General Facility"),
                ],
                default="0000",
                help_text="UN ISIC classification for the primary operations.",
                max_length=10,
                verbose_name="Primary Facility Activity",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="registered_id",
            field=models.CharField(
                blank=True,
                help_text="Business Registration Number (e.g., CUIT, VAT).",
                max_length=100,
                null=True,
                verbose_name="Registered ID",
            ),
        ),
        migrations.CreateModel(
            name="FacilityClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="E.g., Certified ISO 14001 Environmental Management System or Registered WEEE Processing Facility.",
                        max_length=255,
                        verbose_name="Claim Description",
                    ),
                ),
                (
                    "topic_code",
                    models.CharField(
                        choices=[
                            ("environment.waste", "Environment - Waste"),
                            ("environment.energy", "Environment - Energy"),
                            ("environment.emissions", "Environment - Emissions"),
                            ("circularity.content", "Circularity - Content"),
                            ("circularity.design", "Circularity - Design"),
                            ("social.labour", "Social - Labour"),
                            ("governance.compliance", "Governance - Compliance"),
                        ],
                        max_length=50,
                        verbose_name="Conformity Topic",
                    ),
                ),
                (
                    "admin_name",
                    models.CharField(
                        help_text="E.g., Environmental Protection Agency, Ministry of Environment, or ISO.",
                        max_length=255,
                        verbose_name="Administering Body",
                    ),
                ),
                (
                    "admin_url",
                    models.URLField(
                        blank=True,
                        help_text="E.g., https://www.epa.gov/ or https://www.iso.org/",
                        null=True,
                        verbose_name="Administering Body URL",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the audit or certification was granted.",
                        null=True,
                        verbose_name="Assessment Date",
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the certificate PDF or a Digital Conformity Credential (DCC).",
                        max_length=1024,
                        null=True,
                        verbose_name="Evidence URL",
                    ),
                ),
                (
                    "evidence_name",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'ISO 14001 Certificate 2024.pdf'",
                        max_length=255,
                        null=True,
                        verbose_name="Evidence Document Name",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="user.institution",
                    ),
                ),
            ],
        ),
    ]
