# Generated by Django 5.0.6 on 2026-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_remove_institutiondppsettings_schema_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutiondppsettings",
            name="active_dpp_standard",
            field=models.CharField(
                choices=[("untp-0.7.0", "UNTP Standard v0.7.0")],
                default="untp-0.7.0",
                help_text="The DPP standard version your backend will use to format the credentials.",
                max_length=50,
                verbose_name="Active Protocol Standard",
            ),
        ),
    ]
