# Generated by Django 5.0.6 on 2026-09-03 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_institution_process_category_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="facility_id_uri",
            field=models.URLField(
                blank=True,
                help_text="Global URI (or URL) for this facility (e.g., https://www.myweb.com).",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "did"]
                    )
                ],
                verbose_name="Facility ID",
            ),
        ),
    ]
