# Generated by Django 5.0.6 on 2024-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snapshot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="device",
        ),
    ]
