# Generated by Django 5.0.6 on 2024-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "System"),
                    (1, "User"),
                    (2, "Document"),
                    (3, "EraseServer"),
                ]
            ),
        ),
    ]
