# Generated by Django 5.0.6 on 2024-07-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_alter_annotation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="type",
            field=models.SmallIntegerField(
                choices=[(0, "System"), (1, "User"), (2, "Document")]
            ),
        ),
    ]
