# Generated by Django 5.0.6 on 2024-09-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_alter_annotation_type"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.institution"
            ),
        ),
    ]
