# Generated by Django 5.0.6 on 2025-01-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0004_remove_userproperty_user_unique_type_key_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproperty",
            name="type",
            field=models.SmallIntegerField(
                choices=[(1, "User"), (2, "EraseServer")], default=1
            ),
        ),
    ]
