# Generated by Django 5.0.6 on 2025-11-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0006_userproperty_userproperty_unique_type_key_uuid"),
        ("transfer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemproperty",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="transfer.transfer",
            ),
        ),
    ]
