# Generated by Django 5.0.6 on 2025-12-03 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0006_userproperty_userproperty_unique_type_key_uuid"),
        ("user", "0004_alter_institution_algorithm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="systemproperty",
            name="system_unique_type_key_uuid",
        ),
        migrations.AddConstraint(
            model_name="systemproperty",
            constraint=models.UniqueConstraint(
                fields=("key", "value", "uuid"), name="system_unique_type_key_uuid"
            ),
        ),
    ]
