# Generated by Django 5.0.6 on 2026-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0008_credentialproperty"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialproperty",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="E.g. 'Digital Facility Record' or 'Product Passport'",
                max_length=255,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="credentialproperty",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
