# Generated by Django 5.0.6 on 2026-05-27 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0009_credentialproperty_description_and_more"),
        ("user", "0007_alter_institutionsettings_qr_content_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialproperty",
            name="sysprop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credentials",
                to="evidence.systemproperty",
            ),
        ),
        migrations.AlterField(
            model_name="credentialproperty",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name="credentialproperty",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("key", "DPP"), _negated=True),
                    ("sysprop__isnull", False),
                    _connector="OR",
                ),
                name="dpp_must_have_sysprop",
            ),
        ),
    ]
