# Generated by Django 5.0.6 on 2026-06-10 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0010_userproperty_device_id"),
        ("user", "0004_alter_institution_algorithm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rootalias",
            constraint=models.CheckConstraint(
                check=models.Q(("alias__contains", ":"), ("root__contains", ":")),
                name="rootalias_ids_have_algorithm_prefix",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemproperty",
            constraint=models.CheckConstraint(
                check=models.Q(("value__contains", ":")),
                name="systemproperty_value_has_algorithm_prefix",
            ),
        ),
    ]
