# Generated by Django 5.0.6 on 2026-06-19 15:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0011_rootalias_rootalias_ids_have_algorithm_prefix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rootalias",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
