# Generated by Django 5.0.6 on 2026-07-23 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0012_rootalias_created_default"),
        ("user", "0007_institution_process_category_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=256)),
                ("value", models.CharField(max_length=256)),
                ("credential", models.JSONField()),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="E.g. 'Digital Facility Record' or 'Product Passport'",
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.institution",
                    ),
                ),
                (
                    "sysprop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credentials",
                        to="evidence.systemproperty",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="credentialproperty",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("key", "DPP"), _negated=True),
                    ("sysprop__isnull", False),
                    _connector="OR",
                ),
                name="credential_must_have_sysprop",
            ),
        ),
    ]
